export default [
    {
        "name": "3-D Man",
        "alignment": "good",
        "intelligence": 50,
        "strength": 31,
        "speed": 43,
        "durability": 32,
        "power": 25,
        "combat": 52,
        "total": 233
    },
    {
        "name": "A-Bomb",
        "alignment": "good",
        "intelligence": 38,
        "strength": 100,
        "speed": 17,
        "durability": 80,
        "power": 17,
        "combat": 64,
        "total": 316
    },
    {
        "name": "Abe Sapien",
        "alignment": "good",
        "intelligence": 88,
        "strength": 14,
        "speed": 35,
        "durability": 42,
        "power": 35,
        "combat": 85,
        "total": 299
    },
    {
        "name": "Abin Sur",
        "alignment": "good",
        "intelligence": 50,
        "strength": 90,
        "speed": 53,
        "durability": 64,
        "power": 84,
        "combat": 65,
        "total": 406
    },
    {
        "name": "Abomination",
        "alignment": "bad",
        "intelligence": 63,
        "strength": 80,
        "speed": 53,
        "durability": 90,
        "power": 55,
        "combat": 95,
        "total": 436
    },
    {
        "name": "Abraxas",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 100,
        "speed": 83,
        "durability": 99,
        "power": 100,
        "combat": 56,
        "total": 526
    },
    {
        "name": "Adam Monroe",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 12,
        "durability": 100,
        "power": 71,
        "combat": 64,
        "total": 320
    },
    {
        "name": "Adam Strange",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Agent  13",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Agent Bob",
        "alignment": "good",
        "intelligence": 10,
        "strength": 8,
        "speed": 13,
        "durability": 5,
        "power": 5,
        "combat": 20,
        "total": 61
    },
    {
        "name": "Agent Zero",
        "alignment": "good",
        "intelligence": 75,
        "strength": 28,
        "speed": 38,
        "durability": 80,
        "power": 72,
        "combat": 95,
        "total": 388
    },
    {
        "name": "Air-Walker",
        "alignment": "bad",
        "intelligence": 50,
        "strength": 85,
        "speed": 100,
        "durability": 85,
        "power": 100,
        "combat": 40,
        "total": 460
    },
    {
        "name": "Alan Scott",
        "alignment": "good",
        "intelligence": 63,
        "strength": 80,
        "speed": 23,
        "durability": 90,
        "power": 98,
        "combat": 32,
        "total": 386
    },
    {
        "name": "Alex Woolsly",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Alfred Pennyworth",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 17,
        "durability": 10,
        "power": 7,
        "combat": 55,
        "total": 162
    },
    {
        "name": "Allan Quatermain",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Amazo",
        "alignment": "bad",
        "intelligence": 75,
        "strength": 100,
        "speed": 100,
        "durability": 100,
        "power": 100,
        "combat": 100,
        "total": 575
    },
    {
        "name": "Ammo",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Ando Masahashi",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Angel",
        "alignment": "good",
        "intelligence": 63,
        "strength": 13,
        "speed": 46,
        "durability": 64,
        "power": 17,
        "combat": 42,
        "total": 245
    },
    {
        "name": "Angel Salvadore",
        "alignment": "good",
        "intelligence": 38,
        "strength": 10,
        "speed": 28,
        "durability": 28,
        "power": 46,
        "combat": 60,
        "total": 210
    },
    {
        "name": "Angela",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Animal Man",
        "alignment": "good",
        "intelligence": 56,
        "strength": 48,
        "speed": 47,
        "durability": 85,
        "power": 73,
        "combat": 80,
        "total": 389
    },
    {
        "name": "Annihilus",
        "alignment": "bad",
        "intelligence": 75,
        "strength": 80,
        "speed": 47,
        "durability": 56,
        "power": 59,
        "combat": 64,
        "total": 381
    },
    {
        "name": "Ant-Man",
        "alignment": "good",
        "intelligence": 100,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 32,
        "combat": 32,
        "total": 225
    },
    {
        "name": "Ant-Man II",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 32,
        "combat": 28,
        "total": 184
    },
    {
        "name": "Anti-Monitor",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 90,
        "speed": 38,
        "durability": 90,
        "power": 100,
        "combat": 90,
        "total": 496
    },
    {
        "name": "Anti-Spawn",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Anti-Venom",
        "alignment": "",
        "intelligence": 75,
        "strength": 60,
        "speed": 65,
        "durability": 90,
        "power": 85,
        "combat": 84,
        "total": 459
    },
    {
        "name": "Apocalypse",
        "alignment": "bad",
        "intelligence": 100,
        "strength": 100,
        "speed": 33,
        "durability": 100,
        "power": 100,
        "combat": 60,
        "total": 493
    },
    {
        "name": "Aquababy",
        "alignment": "good",
        "intelligence": 10,
        "strength": 16,
        "speed": 12,
        "durability": 14,
        "power": 37,
        "combat": 14,
        "total": 103
    },
    {
        "name": "Aqualad",
        "alignment": "good",
        "intelligence": 63,
        "strength": 44,
        "speed": 42,
        "durability": 75,
        "power": 76,
        "combat": 60,
        "total": 360
    },
    {
        "name": "Aquaman",
        "alignment": "good",
        "intelligence": 63,
        "strength": 80,
        "speed": 50,
        "durability": 80,
        "power": 65,
        "combat": 80,
        "total": 418
    },
    {
        "name": "Arachne",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Archangel",
        "alignment": "good",
        "intelligence": 63,
        "strength": 13,
        "speed": 58,
        "durability": 64,
        "power": 28,
        "combat": 42,
        "total": 268
    },
    {
        "name": "Arclight",
        "alignment": "bad",
        "intelligence": 38,
        "strength": 63,
        "speed": 23,
        "durability": 42,
        "power": 52,
        "combat": 70,
        "total": 288
    },
    {
        "name": "Ares",
        "alignment": "good",
        "intelligence": 75,
        "strength": 82,
        "speed": 35,
        "durability": 80,
        "power": 62,
        "combat": 101,
        "total": 435
    },
    {
        "name": "Ariel",
        "alignment": "good",
        "intelligence": 50,
        "strength": 10,
        "speed": 12,
        "durability": 14,
        "power": 72,
        "combat": 28,
        "total": 186
    },
    {
        "name": "Armor",
        "alignment": "good",
        "intelligence": 50,
        "strength": 63,
        "speed": 12,
        "durability": 80,
        "power": 55,
        "combat": 54,
        "total": 314
    },
    {
        "name": "Arsenal",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Astro Boy",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Atlas",
        "alignment": "good",
        "intelligence": 50,
        "strength": 80,
        "speed": 23,
        "durability": 99,
        "power": 69,
        "combat": 42,
        "total": 363
    },
    {
        "name": "Atom",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Atom Girl",
        "alignment": "good",
        "intelligence": 38,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 38,
        "combat": 42,
        "total": 179
    },
    {
        "name": "Atom I",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Atom II",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Atom III",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Atom IV",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Aurora",
        "alignment": "good",
        "intelligence": 50,
        "strength": 15,
        "speed": 83,
        "durability": 56,
        "power": 69,
        "combat": 56,
        "total": 329
    },
    {
        "name": "Azazel",
        "alignment": "bad",
        "intelligence": 50,
        "strength": 11,
        "speed": 47,
        "durability": 95,
        "power": 87,
        "combat": 80,
        "total": 370
    },
    {
        "name": "Azrael",
        "alignment": "good",
        "intelligence": 63,
        "strength": 18,
        "speed": 17,
        "durability": 20,
        "power": 35,
        "combat": 80,
        "total": 233
    },
    {
        "name": "Aztar",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bane",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 53,
        "speed": 23,
        "durability": 56,
        "power": 51,
        "combat": 95,
        "total": 366
    },
    {
        "name": "Banshee",
        "alignment": "good",
        "intelligence": 50,
        "strength": 10,
        "speed": 58,
        "durability": 42,
        "power": 60,
        "combat": 70,
        "total": 290
    },
    {
        "name": "Bantam",
        "alignment": "good",
        "intelligence": 25,
        "strength": 53,
        "speed": 23,
        "durability": 54,
        "power": 21,
        "combat": 56,
        "total": 232
    },
    {
        "name": "Batgirl I",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Batgirl II",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Batgirl III",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Batgirl IV",
        "alignment": "good",
        "intelligence": 69,
        "strength": 12,
        "speed": 27,
        "durability": 56,
        "power": 42,
        "combat": 100,
        "total": 306
    },
    {
        "name": "Batgirl V",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Batgirl VI",
        "alignment": "good",
        "intelligence": 75,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 22,
        "combat": 80,
        "total": 238
    },
    {
        "name": "Batman",
        "alignment": "good",
        "intelligence": 100,
        "strength": 18,
        "speed": 27,
        "durability": 42,
        "power": 37,
        "combat": 100,
        "total": 324
    },
    {
        "name": "Batman II",
        "alignment": "good",
        "intelligence": 88,
        "strength": 11,
        "speed": 33,
        "durability": 28,
        "power": 36,
        "combat": 100,
        "total": 296
    },
    {
        "name": "Battlestar",
        "alignment": "good",
        "intelligence": 50,
        "strength": 53,
        "speed": 35,
        "durability": 74,
        "power": 48,
        "combat": 74,
        "total": 334
    },
    {
        "name": "Beak",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Beast",
        "alignment": "good",
        "intelligence": 88,
        "strength": 48,
        "speed": 35,
        "durability": 56,
        "power": 35,
        "combat": 84,
        "total": 346
    },
    {
        "name": "Beast Boy",
        "alignment": "good",
        "intelligence": 50,
        "strength": 28,
        "speed": 50,
        "durability": 70,
        "power": 79,
        "combat": 40,
        "total": 317
    },
    {
        "name": "Beetle",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Ben 10",
        "alignment": "good",
        "intelligence": 10,
        "strength": 7,
        "speed": 8,
        "durability": 10,
        "power": 90,
        "combat": 40,
        "total": 165
    },
    {
        "name": "Beta Ray Bill",
        "alignment": "good",
        "intelligence": 63,
        "strength": 80,
        "speed": 35,
        "durability": 95,
        "power": 100,
        "combat": 84,
        "total": 457
    },
    {
        "name": "Beyonder",
        "alignment": "good",
        "intelligence": 88,
        "strength": 100,
        "speed": 23,
        "durability": 100,
        "power": 100,
        "combat": 56,
        "total": 467
    },
    {
        "name": "Big Barda",
        "alignment": "good",
        "intelligence": 63,
        "strength": 90,
        "speed": 23,
        "durability": 85,
        "power": 42,
        "combat": 72,
        "total": 375
    },
    {
        "name": "Big Daddy",
        "alignment": "good",
        "intelligence": 38,
        "strength": 10,
        "speed": 12,
        "durability": 32,
        "power": 22,
        "combat": 64,
        "total": 178
    },
    {
        "name": "Big Man",
        "alignment": "bad",
        "intelligence": 75,
        "strength": 12,
        "speed": 23,
        "durability": 28,
        "power": 19,
        "combat": 70,
        "total": 227
    },
    {
        "name": "Bill Harken",
        "alignment": "good",
        "intelligence": 63,
        "strength": 36,
        "speed": 33,
        "durability": 60,
        "power": 23,
        "combat": 40,
        "total": 255
    },
    {
        "name": "Billy Kincaid",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Binary",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bird-Brain",
        "alignment": "good",
        "intelligence": 25,
        "strength": 10,
        "speed": 35,
        "durability": 28,
        "power": 21,
        "combat": 42,
        "total": 161
    },
    {
        "name": "Bird-Man",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bird-Man II",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Birdman",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bishop",
        "alignment": "good",
        "intelligence": 63,
        "strength": 14,
        "speed": 23,
        "durability": 75,
        "power": 85,
        "combat": 65,
        "total": 325
    },
    {
        "name": "Bizarro",
        "alignment": "neutral",
        "intelligence": 75,
        "strength": 95,
        "speed": 100,
        "durability": 100,
        "power": 95,
        "combat": 85,
        "total": 550
    },
    {
        "name": "Black Abbott",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Black Adam",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 100,
        "speed": 92,
        "durability": 100,
        "power": 89,
        "combat": 56,
        "total": 525
    },
    {
        "name": "Black Bolt",
        "alignment": "good",
        "intelligence": 75,
        "strength": 67,
        "speed": 100,
        "durability": 84,
        "power": 100,
        "combat": 56,
        "total": 482
    },
    {
        "name": "Black Canary I",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Black Canary II",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Black Cat",
        "alignment": "good",
        "intelligence": 75,
        "strength": 16,
        "speed": 33,
        "durability": 10,
        "power": 23,
        "combat": 70,
        "total": 227
    },
    {
        "name": "Black Goliath",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Black Knight III",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 8,
        "durability": 70,
        "power": 43,
        "combat": 70,
        "total": 264
    },
    {
        "name": "Black Lightning",
        "alignment": "good",
        "intelligence": 50,
        "strength": 11,
        "speed": 53,
        "durability": 28,
        "power": 70,
        "combat": 75,
        "total": 287
    },
    {
        "name": "Black Mamba",
        "alignment": "bad",
        "intelligence": 75,
        "strength": 10,
        "speed": 35,
        "durability": 42,
        "power": 78,
        "combat": 65,
        "total": 305
    },
    {
        "name": "Black Panther",
        "alignment": "good",
        "intelligence": 88,
        "strength": 16,
        "speed": 30,
        "durability": 60,
        "power": 41,
        "combat": 100,
        "total": 335
    },
    {
        "name": "Black Widow",
        "alignment": "good",
        "intelligence": 75,
        "strength": 13,
        "speed": 27,
        "durability": 32,
        "power": 32,
        "combat": 100,
        "total": 279
    },
    {
        "name": "Black Widow II",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blackout",
        "alignment": "bad",
        "intelligence": 63,
        "strength": 32,
        "speed": 45,
        "durability": 80,
        "power": 38,
        "combat": 65,
        "total": 323
    },
    {
        "name": "Blackwing",
        "alignment": "bad",
        "intelligence": 38,
        "strength": 10,
        "speed": 35,
        "durability": 32,
        "power": 20,
        "combat": 56,
        "total": 191
    },
    {
        "name": "Blackwulf",
        "alignment": "",
        "intelligence": 50,
        "strength": 28,
        "speed": 8,
        "durability": 30,
        "power": 59,
        "combat": 25,
        "total": 200
    },
    {
        "name": "Blade",
        "alignment": "good",
        "intelligence": 63,
        "strength": 28,
        "speed": 38,
        "durability": 50,
        "power": 33,
        "combat": 90,
        "total": 302
    },
    {
        "name": "Blaquesmith",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bling!",
        "alignment": "good",
        "intelligence": 69,
        "strength": 14,
        "speed": 12,
        "durability": 90,
        "power": 52,
        "combat": 28,
        "total": 265
    },
    {
        "name": "Blink",
        "alignment": "good",
        "intelligence": 50,
        "strength": 8,
        "speed": 20,
        "durability": 28,
        "power": 55,
        "combat": 64,
        "total": 225
    },
    {
        "name": "Blizzard",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blizzard I",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blizzard II",
        "alignment": "bad",
        "intelligence": 38,
        "strength": 10,
        "speed": 27,
        "durability": 42,
        "power": 47,
        "combat": 56,
        "total": 220
    },
    {
        "name": "Blob",
        "alignment": "bad",
        "intelligence": 10,
        "strength": 83,
        "speed": 23,
        "durability": 95,
        "power": 26,
        "combat": 72,
        "total": 309
    },
    {
        "name": "Bloodaxe",
        "alignment": "bad",
        "intelligence": 63,
        "strength": 80,
        "speed": 33,
        "durability": 80,
        "power": 84,
        "combat": 84,
        "total": 424
    },
    {
        "name": "Bloodhawk",
        "alignment": "good",
        "intelligence": 50,
        "strength": 10,
        "speed": 50,
        "durability": 80,
        "power": 66,
        "combat": 64,
        "total": 320
    },
    {
        "name": "Bloodwraith",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blue Beetle",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blue Beetle I",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blue Beetle II",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Blue Beetle III",
        "alignment": "good",
        "intelligence": 50,
        "strength": 34,
        "speed": 58,
        "durability": 80,
        "power": 97,
        "combat": 30,
        "total": 349
    },
    {
        "name": "Bolt",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bomb Queen",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Boom Boom",
        "alignment": "good",
        "intelligence": 38,
        "strength": 10,
        "speed": 12,
        "durability": 42,
        "power": 56,
        "combat": 64,
        "total": 222
    },
    {
        "name": "Boomer",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Booster Gold",
        "alignment": "good",
        "intelligence": 56,
        "strength": 85,
        "speed": 53,
        "durability": 50,
        "power": 72,
        "combat": 40,
        "total": 356
    },
    {
        "name": "Box",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Box III",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Box IV",
        "alignment": "good",
        "intelligence": 50,
        "strength": 75,
        "speed": 23,
        "durability": 28,
        "power": 11,
        "combat": 56,
        "total": 243
    },
    {
        "name": "Brainiac",
        "alignment": "bad",
        "intelligence": 100,
        "strength": 28,
        "speed": 63,
        "durability": 90,
        "power": 60,
        "combat": 75,
        "total": 416
    },
    {
        "name": "Brainiac 5",
        "alignment": "good",
        "intelligence": 100,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 60,
        "combat": 32,
        "total": 253
    },
    {
        "name": "Brother Voodoo",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bullseye",
        "alignment": "bad",
        "intelligence": 50,
        "strength": 11,
        "speed": 25,
        "durability": 70,
        "power": 20,
        "combat": 70,
        "total": 246
    },
    {
        "name": "Bumblebee",
        "alignment": "good",
        "intelligence": 63,
        "strength": 28,
        "speed": 25,
        "durability": 10,
        "power": 45,
        "combat": 35,
        "total": 206
    },
    {
        "name": "Bumbleboy",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Bushido",
        "alignment": "good",
        "intelligence": 38,
        "strength": 10,
        "speed": 8,
        "durability": 10,
        "power": 19,
        "combat": 70,
        "total": 155
    },
    {
        "name": "Cable",
        "alignment": "good",
        "intelligence": 88,
        "strength": 48,
        "speed": 23,
        "durability": 56,
        "power": 100,
        "combat": 80,
        "total": 395
    },
    {
        "name": "Callisto",
        "alignment": "bad",
        "intelligence": 63,
        "strength": 53,
        "speed": 23,
        "durability": 42,
        "power": 45,
        "combat": 85,
        "total": 311
    },
    {
        "name": "Cameron Hicks",
        "alignment": "good",
        "intelligence": 50,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 51,
        "combat": 70,
        "total": 232
    },
    {
        "name": "Cannonball",
        "alignment": "good",
        "intelligence": 50,
        "strength": 28,
        "speed": 67,
        "durability": 99,
        "power": 79,
        "combat": 56,
        "total": 379
    },
    {
        "name": "Captain America",
        "alignment": "good",
        "intelligence": 63,
        "strength": 19,
        "speed": 35,
        "durability": 56,
        "power": 46,
        "combat": 100,
        "total": 319
    },
    {
        "name": "Captain Atom",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Captain Britain",
        "alignment": "good",
        "intelligence": 75,
        "strength": 77,
        "speed": 50,
        "durability": 60,
        "power": 31,
        "combat": 80,
        "total": 373
    },
    {
        "name": "Captain Epic",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Captain Mar-vell",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Captain Marvel",
        "alignment": "good",
        "intelligence": 100,
        "strength": 100,
        "speed": 67,
        "durability": 95,
        "power": 62,
        "combat": 56,
        "total": 480
    },
    {
        "name": "Captain Marvel II",
        "alignment": "good",
        "intelligence": 75,
        "strength": 81,
        "speed": 27,
        "durability": 90,
        "power": 34,
        "combat": 56,
        "total": 363
    },
    {
        "name": "Captain Planet",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Captain Universe",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Carnage",
        "alignment": "bad",
        "intelligence": 63,
        "strength": 63,
        "speed": 70,
        "durability": 84,
        "power": 81,
        "combat": 90,
        "total": 451
    },
    {
        "name": "Cat",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Cat II",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Catwoman",
        "alignment": "good",
        "intelligence": 63,
        "strength": 13,
        "speed": 33,
        "durability": 28,
        "power": 24,
        "combat": 85,
        "total": 246
    },
    {
        "name": "Cecilia Reyes",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Century",
        "alignment": "good",
        "intelligence": 88,
        "strength": 80,
        "speed": 53,
        "durability": 64,
        "power": 74,
        "combat": 100,
        "total": 459
    },
    {
        "name": "Cerebra",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Chamber",
        "alignment": "good",
        "intelligence": 50,
        "strength": 10,
        "speed": 20,
        "durability": 80,
        "power": 57,
        "combat": 64,
        "total": 281
    },
    {
        "name": "Chameleon",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 10,
        "speed": 12,
        "durability": 28,
        "power": 28,
        "combat": 28,
        "total": 194
    },
    {
        "name": "Changeling",
        "alignment": "bad",
        "intelligence": 63,
        "strength": 10,
        "speed": 23,
        "durability": 42,
        "power": 64,
        "combat": 64,
        "total": 266
    },
    {
        "name": "Cheetah I",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Cheetah II",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Cheetah III",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Chromos",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Chuck Norris",
        "alignment": "good",
        "intelligence": 50,
        "strength": 80,
        "speed": 47,
        "durability": 56,
        "power": 42,
        "combat": 99,
        "total": 374
    },
    {
        "name": "Claire Bennet",
        "alignment": "good",
        "intelligence": 38,
        "strength": 9,
        "speed": 12,
        "durability": 100,
        "power": 73,
        "combat": 28,
        "total": 260
    },
    {
        "name": "Clea",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Cloak",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 47,
        "durability": 64,
        "power": 74,
        "combat": 56,
        "total": 314
    },
    {
        "name": "Cogliostro",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Colin Wagner",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Colossal Boy",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Colossus",
        "alignment": "good",
        "intelligence": 63,
        "strength": 83,
        "speed": 33,
        "durability": 100,
        "power": 46,
        "combat": 80,
        "total": 405
    },
    {
        "name": "Corsair",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Crimson Crusader",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Crimson Dynamo I",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Crystal",
        "alignment": "good",
        "intelligence": 63,
        "strength": 16,
        "speed": 12,
        "durability": 14,
        "power": 57,
        "combat": 56,
        "total": 218
    },
    {
        "name": "Curse",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Cy-Gor",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Cyborg",
        "alignment": "good",
        "intelligence": 75,
        "strength": 53,
        "speed": 42,
        "durability": 85,
        "power": 72,
        "combat": 64,
        "total": 391
    },
    {
        "name": "Cyborg Superman",
        "alignment": "bad",
        "intelligence": 75,
        "strength": 93,
        "speed": 92,
        "durability": 100,
        "power": 100,
        "combat": 80,
        "total": 540
    },
    {
        "name": "Cyclops",
        "alignment": "good",
        "intelligence": 75,
        "strength": 10,
        "speed": 23,
        "durability": 42,
        "power": 76,
        "combat": 80,
        "total": 306
    },
    {
        "name": "Cypher",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Dagger",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 35,
        "durability": 42,
        "power": 52,
        "combat": 70,
        "total": 272
    },
    {
        "name": "Danny Cooper",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Daphne Powell",
        "alignment": "good",
        "intelligence": 38,
        "strength": 10,
        "speed": 8,
        "durability": 10,
        "power": 56,
        "combat": 10,
        "total": 132
    },
    {
        "name": "Daredevil",
        "alignment": "good",
        "intelligence": 75,
        "strength": 13,
        "speed": 27,
        "durability": 28,
        "power": 57,
        "combat": 95,
        "total": 295
    },
    {
        "name": "Darkhawk",
        "alignment": "good",
        "intelligence": 50,
        "strength": 32,
        "speed": 33,
        "durability": 70,
        "power": 74,
        "combat": 64,
        "total": 323
    },
    {
        "name": "Darkman",
        "alignment": "good",
        "intelligence": 75,
        "strength": 14,
        "speed": 23,
        "durability": 85,
        "power": 12,
        "combat": 28,
        "total": 237
    },
    {
        "name": "Darkseid",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 100,
        "speed": 23,
        "durability": 100,
        "power": 100,
        "combat": 95,
        "total": 506
    },
    {
        "name": "Darkside",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Darkstar",
        "alignment": "good",
        "intelligence": 38,
        "strength": 8,
        "speed": 35,
        "durability": 42,
        "power": 52,
        "combat": 64,
        "total": 239
    },
    {
        "name": "Dash",
        "alignment": "good",
        "intelligence": 9,
        "strength": 4,
        "speed": 83,
        "durability": 42,
        "power": 12,
        "combat": 28,
        "total": 178
    },
    {
        "name": "Dazzler",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 35,
        "durability": 42,
        "power": 64,
        "combat": 56,
        "total": 270
    },
    {
        "name": "Deadman",
        "alignment": "good",
        "intelligence": 50,
        "strength": 10,
        "speed": 33,
        "durability": 100,
        "power": 100,
        "combat": 42,
        "total": 335
    },
    {
        "name": "Deadpool",
        "alignment": "neutral",
        "intelligence": 50,
        "strength": 15,
        "speed": 30,
        "durability": 100,
        "power": 100,
        "combat": 100,
        "total": 395
    },
    {
        "name": "Deadshot",
        "alignment": "bad",
        "intelligence": 50,
        "strength": 10,
        "speed": 23,
        "durability": 28,
        "power": 47,
        "combat": 80,
        "total": 238
    },
    {
        "name": "Deathlok",
        "alignment": "good",
        "intelligence": 69,
        "strength": 32,
        "speed": 30,
        "durability": 70,
        "power": 40,
        "combat": 60,
        "total": 301
    },
    {
        "name": "Deathstroke",
        "alignment": "neutral",
        "intelligence": 75,
        "strength": 30,
        "speed": 35,
        "durability": 100,
        "power": 36,
        "combat": 90,
        "total": 366
    },
    {
        "name": "Demogoblin",
        "alignment": "bad",
        "intelligence": 50,
        "strength": 48,
        "speed": 42,
        "durability": 35,
        "power": 54,
        "combat": 60,
        "total": 289
    },
    {
        "name": "Destroyer",
        "alignment": "bad",
        "intelligence": 50,
        "strength": 95,
        "speed": 58,
        "durability": 98,
        "power": 90,
        "combat": 70,
        "total": 461
    },
    {
        "name": "DL Hawkins",
        "alignment": "good",
        "intelligence": 50,
        "strength": 12,
        "speed": 12,
        "durability": 56,
        "power": 48,
        "combat": 56,
        "total": 234
    },
    {
        "name": "Doc Samson",
        "alignment": "good",
        "intelligence": 75,
        "strength": 80,
        "speed": 33,
        "durability": 80,
        "power": 36,
        "combat": 70,
        "total": 374
    },
    {
        "name": "Doctor Doom",
        "alignment": "bad",
        "intelligence": 100,
        "strength": 32,
        "speed": 20,
        "durability": 100,
        "power": 93,
        "combat": 84,
        "total": 429
    },
    {
        "name": "Doctor Doom II",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 32,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 36
    },
    {
        "name": "Doctor Fate",
        "alignment": "good",
        "intelligence": 81,
        "strength": 16,
        "speed": 25,
        "durability": 80,
        "power": 100,
        "combat": 50,
        "total": 352
    },
    {
        "name": "Doctor Octopus",
        "alignment": "bad",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Doctor Strange",
        "alignment": "good",
        "intelligence": 100,
        "strength": 10,
        "speed": 12,
        "durability": 84,
        "power": 100,
        "combat": 60,
        "total": 366
    },
    {
        "name": "Domino",
        "alignment": "good",
        "intelligence": 63,
        "strength": 10,
        "speed": 27,
        "durability": 28,
        "power": 49,
        "combat": 74,
        "total": 251
    },
    {
        "name": "Donna Troy",
        "alignment": "good",
        "intelligence": 1,
        "strength": 1,
        "speed": 1,
        "durability": 1,
        "power": 0,
        "combat": 1,
        "total": 5
    },
    {
        "name": "Doomsday",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 80,
        "speed": 67,
        "durability": 120,
        "power": 100,
        "combat": 90,
        "total": 545
    },
    {
        "name": "Doppelganger",
        "alignment": "bad",
        "intelligence": 8,
        "strength": 63,
        "speed": 60,
        "durability": 95,
        "power": 62,
        "combat": 84,
        "total": 372
    },
    {
        "name": "Dormammu",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 95,
        "speed": 83,
        "durability": 100,
        "power": 100,
        "combat": 80,
        "total": 546
    },
    {
        "name": "Dr Manhattan",
        "alignment": "good",
        "intelligence": 88,
        "strength": 32,
        "speed": 42,
        "durability": 95,
        "power": 100,
        "combat": 42,
        "total": 399
    },
    {
        "name": "Ego",
        "alignment": "bad",
        "intelligence": 88,
        "strength": 80,
        "speed": 83,
        "durability": 99,
        "power": 71,
        "combat": 28,
        "total": 449
    },
    {
        "name": "Elastigirl",
        "alignment": "good",
        "intelligence": 38,
        "strength": 32,
        "speed": 12,
        "durability": 90,
        "power": 20,
        "combat": 14,
        "total": 206
    },
]